### PR TITLE
Enhance (ui): Adds examples of 'checkbox' and 'select' fields

### PR DESCRIPTION
**Pull request by martinhbramwell**
Hi Justin,

I've been wrestling with your additional fields trying to understand how to include them in my project.  I've got 'checkbox' and 'select' working -- sort of.

I didn't see a good way to provide an initial value for the select list apart from initializing the form.  That worked when I supplied each and every field with a value. Missing even one completely locked up my browser!  I have created new issue -- #9.

Signed-off-by: Martin Bramwell <martinhbramwell@gmail.com>

### CODE REVIEW

**Comment by justin-schroeder** [comment]
You can set initial values on fields by either passing an object `{fieldname: 'value'}` as the initial prop, or on a field by field bases just passing the `value`. For example, from your PR:

```
<formulate-element
  id="fatuous"
  name="qualities"
  type="select"
  label="Pick a role for your spirit animal to play?"
  initial="wall"
  :options="[
    { id: 'alpha', name: 'Alpha male', value: 'alpha', label: 'Alpha male', },
    { id: 'wall', name: 'Wallflower', value: 'wall', label: 'Wallflower', },
    { id: 'chair', name: 'Armchair General', value: 'chair', label: 'Armchair General', },
    { id: 'qback', name: 'Monday Morning Quarterback', value: 'qback', label: 'Monday Morning Quarterback', },
  ]"
/>
```

In regards to #9 I believe the browser is locking up because you are directly passing an object literal. If you move the values of your `:initial` prop to a `data()` value and pass that in instead `:initial="initialValues"` I believe your bug goes away.

**Comment by martinhbramwell** [comment]
Hi Justin
So, everything you suggested worked the first time.  Thank you!

However, it took me a lot longer than I would have wanted digging through your code to figure out how to get to the point you have seen. I suspect others will feel the same way. I supplied the pull request as a way to contribute to your project documentation.  I had hoped you would use it.  ( feel free to pick different text :-) )

I fixed the issues and committed a new version, just now.

Rgds,
Martin

**Comment by justin-schroeder** [comment]
@martinhbramwell Thanks! Can you request a new PR with only the documentation updates please?

**Comment by martinhbramwell** [comment]
I think you misunderstood me.  I made no edits to text documentation.  What I did was add some fields to your example app.   In my view examples are part of a project's documentation -- often the most important part.

**Comment by justin-schroeder** [comment]
Great! Can you then please submit another PR with the example field? Please ensure it complies with rules in the `.eslintrc.js`.

**Pull request closed without merging**
