### PR TITLE
Add example dir

### PR DESCRIPTION
**Pull request by martinhbramwell**
I was delighted to find your package, and really want to use it, but I cannot get started based just on your documentation.

Since I wished you had also provided a working example, to examine so as to understand where I went wrong, I thought I'd provide you with a NON-working example, that shows how far I got with the documentation as it is.

Currently, I'm stuck.  I have no idea how to get a form to actually appear. If you could give my example a try and tell me how I screwed up, I'll try to fix it.  Of course, if you want to accept the PR, fix it and commit it, that'd be even better. ;-)

### CODE REVIEW

**Comment by justin-schroeder** [comment]
Appreciate the PR, and I'm happy to help as well. Its really high on my priority list to get some great documentation written up. I'll take a look at this and try to integrate it sometime next week.

**Comment by martinhbramwell** [comment]
Hi Justin, I'm working on some server-side stuff while waiting to hear from you about how to get properly started.  Have you had a look at what I did, to see if the problem isn't just some simple obvious misreading of the docs?

**Comment by justin-schroeder** [comment]
Hello @martinhbramwell! Good news, I've figured out what was causing your issue, and it was indeed an error in the documentation. The function `formulateState()` is a curried function since vuex expects states to be functions, it returns a function. However since the documentation (and you) was destructuring the return value it was getting angry (you cant destructure a function).

The easy fix to this is to just call the curried function:

```js
const state = {
  ...formulateState()()
}
```

I've updated the documentation to reflect this in a new branch that I've submitted as my own PR for others to review. Also I've mostly re-written the example to be something we would be excited to include in this repo. You can download and review that PR/branch here:

https://github.com/wearebraid/vue-formulate/pull/2

Thanks again for contributing, let me know if you have other issues.

**Comment by martinhbramwell** [comment]
Got it going!!  Yay!  Thanks so much!

**Pull request closed without merging**
